# Getting started with ndarray

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy. Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

In [1]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [2]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(an_array.shape)

(3,)


In [3]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2])  

3 33 333


In [4]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


## How to create a Rank 2 numpy array:

A rank 2 ndarray is one with two dimensions. Notice the format below of [ [row] , [row] ]. 2 dimensional arrays are great for representing matrices which are often useful in data science.

In [5]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  12 ,  21


### There are many way to create numpy arrays:

Creating a number of different size arrays with different shapes and different pre-filled values. numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [6]:
# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)

[[0. 0.]
 [0. 0.]]


In [7]:
# create a 2x2 arra filled with 9.0
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [8]:
# create a 2x2 array matrix with a diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [9]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [10]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [11]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.12265335 0.12499835]
 [0.5604437  0.17546973]]


## Array indexing

### Slice indexing

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

In [25]:
# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [26]:
a_slice = an_array[:2, 1:3]  # grab rows index 0, 1 not including 2(:2) then column index 1, 2(1:3)
print(a_slice)

[[12 13]
 [22 23]]


In [27]:
b_slice = np.array(an_array[:2, 1:3])  # making a copy of array grab rows index 0, 1 not including 2(:2) then column index 1, 2(1:3)
print(a_slice)

[[12 13]
 [22 23]]


When you modify a slice, you actually modify the underlying array.

In [28]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])    

Before: 12
After: 1000


In [30]:
print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
b_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])  

Before: 1000
After: 1000


## Use both integer indexing & slice indexing

We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [31]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [32]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [33]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [34]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


## Array Indexing for changing elements:

Sometimes it's useful to use an array of indexes to access or change elements.

In [35]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [36]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [37]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)           

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [38]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [39]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Boolean Indexing

<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

In [40]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [41]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [42]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [43]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[an_array > 15]

array([21, 22, 31, 32])

In [44]:
# alternatively,
an_array [(an_array > 20) & (an_array <30)]

array([21, 22])

In [45]:
# For even values;
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter. Let's add 100 to all the even values.

In [46]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Datatypes and Array Operations

<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>


In [49]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

int64


In [50]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [51]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

int64


In [52]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [53]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


##### Arithmetic Array Operations:

In [54]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [55]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [56]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [57]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [58]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [59]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [60]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Statistical Methods, Sorting, and Set Operations:
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Basic Statistical Operations:
</p>

In [64]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -1.36809102  21.38382884  -0.57309882   2.34356953   1.18650637]
 [ -3.24822513 -13.74856676 -11.4849971    6.21876193  -8.19155423]]


In [65]:
# compute the mean for all elements
print(arr.mean())

-0.7481866388664202


In [66]:
# compute the means by row
print(arr.mean(axis = 1))

[ 4.59454298 -6.09091626]


In [67]:
# compute the means by column
print(arr.mean(axis = 0))

[-2.30815807  3.81763104 -6.02904796  4.28116573 -3.50252393]


In [68]:
# sum all the elements
print(arr.sum())

-7.481866388664202


In [70]:
# compute the medians for each row
print(np.median(arr, axis = 1))

[ 1.18650637 -8.19155423]


In [69]:
# compute the medians for each column
print(np.median(arr, axis = 0))

[-2.30815807  3.81763104 -6.02904796  4.28116573 -3.50252393]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Sorting:
</p>


In [71]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[ 0.01544048  0.13559935  0.46992958  1.62076646  0.73790371 -1.60413902
  0.39808531 -0.3963784  -0.55723381  0.11559113]


In [72]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()
print(sorted)
print()
print(unsorted)

[-1.60413902 -0.55723381 -0.3963784   0.01544048  0.11559113  0.13559935
  0.39808531  0.46992958  0.73790371  1.62076646]

[ 0.01544048  0.13559935  0.46992958  1.62076646  0.73790371 -1.60413902
  0.39808531 -0.3963784  -0.55723381  0.11559113]


In [73]:
# inplace sorting
unsorted.sort()
print(unsorted)

[-1.60413902 -0.55723381 -0.3963784   0.01544048  0.11559113  0.13559935
  0.39808531  0.46992958  0.73790371  1.62076646]


array([-1.60413902, -0.55723381, -0.3963784 ,  0.01544048,  0.11559113,
        0.13559935,  0.39808531,  0.46992958,  0.73790371,  1.62076646])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Finding Unique elements:
</p>

In [75]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Set Operations with np.array data type:
</p>

In [76]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [77]:
# 'intersect1d' elements that are common to both arrays(intersects expects 1d array)
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [78]:
# all unque elements in both 
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [80]:
# Elements in s1 that are not in s2
print(np.setdiff1d(s1,s2))

['desk']


In [81]:
# boolean of which elements of s1 is also in s2
print(np.in1d(s1,s2))

[False  True  True]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>  
Broadcasting:
<br><br>
</p>

In [82]:
start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [83]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [84]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [85]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T# transpose

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [86]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [87]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [88]:
a = np.array([[0,0],[0,0]])
b1 = np.array([1,1])
b2 = 1
print(a+b1)
print(a+b2)

[[1 1]
 [1 1]]
[[1 1]
 [1 1]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [89]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [90]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [91]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000507 seconds


In [92]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [93]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.004759 seconds
